### ISSUE TITLE
Unable to send metrics to ddb

### ISSUE THREAD

**Issue by jbuijgers** [dalmatinerdb/ddb_client#10]
I can only imagine this being an error on my side, but I am unable to get any metrics in DalmatinerDB using this client (or any other). Below are the files I am using in my setup.

docker-compose.yml
```
version: '3' 
services:
  dfe:
    image: projectfifo/dfe
    depends_on:
      - ddb
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_NODE: ddb
      PG_NODE: postgres
    volumes:
      - dfe-data:/data/dalmatinerfe/db
  ddb:
    image: projectfifo/ddb
    volumes:
      - ddb-data:/data/dalmatinerdb/db
    ports:
      - "5555:5555"
  postgres:
    image: projectfifo/metric_metadata
    volumes:
      - postgres-data:/var/lib/postgresql/data
  erlang:
    image: erlang:19.2.3
    working_dir: /opt/project
    volumes:
      - .:/opt/project
    depends_on:
      - ddb

volumes:
  ddb-data:
  dfe-data:
  postgres-data:
```

send-data.erl
```
#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa _build/default/lib/ddb_client/ebin _build/default/lib/dproto/ebin _build/default/lib/mmath/ebin _build/default/lib/snappiest/ebin

main(_) ->
  {ok, Con} = ddb_tcp:connect("ddb", 5555),
  Bucket = <<"my_bucket1">>,
  Delay = 1,
  {ok, SCon} = ddb_tcp:stream_mode(Bucket, Delay, Con),

  Timestamp = 1466072419,
  Metric = dproto:metric_from_list([<<"abc">>, <<"def">>]),
  Value  = mmath_bin:from_list([10.0, 20.5, 30.9]),
  {ok, SCon1} = ddb_tcp:send(Metric, Timestamp, Value, SCon),

  ddb_tcp:close(SCon1).
```

get-data.erl
```
#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa _build/default/lib/ddb_client/ebin _build/default/lib/dproto/ebin _build/default/lib/mmath/ebin _build/default/lib/snappiest/ebin

main(_) ->
  {ok, Con} = ddb_tcp:connect("ddb", 5555),

  Timestamp = 1466072419,
  Bucket = <<"my_bucket">>,
  Metric = dproto:metric_from_list([<<"abc">>, <<"def">>]),
  Count = 3,
  Opts = [{rr, off}, {r, 1}],
  {ok, Data, Con1} = ddb_tcp:get(Bucket, Metric, Timestamp, Count, Opts, Con),

  io:format(Data),

  ddb_tcp:close(Con1).
```

The get-data.erl script produces no output (in the Data var), nor is the metric visible in dfe. The ddb console output after executing get-data.erl:
```
[warning] <0.898.0>@metric_io:do_read:739 [IO] Unknown metric: <<"my_bucket">>/<<3,97,98,99,3,100,101,102>>
```

I've also tried the node and python clients, so not sure if this is the right place to create this issue, as that would point to this being related to something like the docker setup.
